import React, { useEffect, useMemo, useState } from "react";
import ReactDOM from "react-dom/client";
import axios from "axios";
import "./index.css";

const API = process.env.REACT_APP_API_URL || "http://localhost:3002/api";

const api = axios.create({ baseURL: API });
api.interceptors.request.use((config) => {
  const token = localStorage.getItem("fundsroom_token");
  if (token) config.headers.Authorization = `Bearer ${token}`;
  return config;
});

const roles = ["ADMIN", "SALES", "WAREHOUSE", "ACCOUNTS"];

function Login({ onLogin }) {
  const [email, setEmail] = useState("admin@fundsroom.local");
  const [password, setPassword] = useState("FundsRoom@123");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const submit = async (e) => {
    e.preventDefault(); setError(""); setLoading(true);
    try { const { data } = await api.post("/auth/login", { email, password }); localStorage.setItem("fundsroom_token", data.token); localStorage.setItem("fundsroom_user", JSON.stringify(data.user)); onLogin(data.user); }
    catch (err) { setError(err.response?.data?.message || "Login failed"); }
    finally { setLoading(false); }
  };

  return <div className="login-page"><div className="login-card"><div className="brand-mark">FR</div><h1>FundsRoom</h1><p className="muted">Operations & Inventory Portal</p><form onSubmit={submit}><label>Email</label><input value={email} onChange={e => setEmail(e.target.value)} type="email" /><label>Password</label><input value={password} onChange={e => setPassword(e.target.value)} type="password" />{error && <div className="error">{error}</div>}<button className="primary full" disabled={loading}>{loading ? "Signing in..." : "Sign in"}</button></form><div className="demo-note">Demo password: FundsRoom@123<br/>Try admin, sales, warehouse or accounts emails.</div></div></div>;
}

function Layout({ user, page, setPage, children, logout }) {
  const menu = [
    ["dashboard", "Dashboard", ["ADMIN", "SALES", "WAREHOUSE", "ACCOUNTS"]],
    ["customers", "Customers", ["ADMIN", "SALES", "WAREHOUSE", "ACCOUNTS"]],
    ["products", "Products", ["ADMIN", "WAREHOUSE", "SALES", "ACCOUNTS"]],
    ["inventory", "Inventory", ["ADMIN", "WAREHOUSE"]],
    ["challans", "Sales Challans", ["ADMIN", "SALES", "ACCOUNTS", "WAREHOUSE"]],
    ["movements", "Stock Movements", ["ADMIN", "WAREHOUSE", "ACCOUNTS"]],
    ["users", "Users", ["ADMIN"]]
  ];
  return <div className="app-shell"><aside><div className="side-brand"><span>FR</span><div><strong>FundsRoom</strong><small>Operations Portal</small></div></div><div className="role-chip">{user.role}</div><nav>{menu.filter(x => x[2].includes(user.role)).map(([id, label]) => <button key={id} className={page === id ? "nav-item active" : "nav-item"} onClick={() => setPage(id)}>{label}</button>)}</nav><button className="logout" onClick={logout}>Logout</button></aside><main><header><div><span className="eyebrow">BUSINESS OPERATIONS</span><h2>{menu.find(x => x[0] === page)?.[1] || "Dashboard"}</h2></div><div className="user-pill"><div className="avatar">{user.name.split(" ").map(x => x[0]).join("").slice(0,2)}</div><div><strong>{user.name}</strong><small>{user.email}</small></div></div></header><div className="content">{children}</div></main></div>;
}

function Stat({ label, value, sub, alert }) { return <div className="stat"><span>{label}</span><strong className={alert ? "alert-text" : ""}>{value}</strong><small>{sub}</small></div>; }

function DashboardPage() {
  const [summary, setSummary] = useState(null); const [challans, setChallans] = useState([]); const [products, setProducts] = useState([]);
  useEffect(() => { Promise.all([api.get("/dashboard/summary"), api.get("/challans"), api.get("/products")]).then(([s,c,p]) => { setSummary(s.data.data); setChallans(c.data.data.slice(0,5)); setProducts(p.data.data.filter(x => x.currentStock <= x.minimumStock).slice(0,5)); }); }, []);
  return <><div className="hero-row"><div><h3>Good to see you back 👋</h3><p>Monitor customers, stock and sales operations from one place.</p></div><span className="live-dot">● Live data</span></div>{summary && <div className="stats-grid"><Stat label="Customers" value={summary.customers} sub="CRM records"/><Stat label="Products" value={summary.products} sub="SKUs managed"/><Stat label="Pending Challans" value={summary.pendingChallans} sub="Awaiting confirmation"/><Stat label="Low Stock" value={summary.lowStock} sub="Needs attention" alert/></div>}<div className="two-col"><section className="panel"><div className="panel-head"><h3>Recent Challans</h3><span>Latest activity</span></div>{challans.map(c => <div className="list-row" key={c._id}><div><strong>{c.challanNumber}</strong><small>{c.customer?.businessName || c.customer?.name}</small></div><span className={`badge ${c.status.toLowerCase()}`}>{c.status}</span></div>)}{!challans.length && <Empty text="No challans yet"/>}</section><section className="panel"><div className="panel-head"><h3>Low Stock</h3><span>Reorder alerts</span></div>{products.map(p => <div className="list-row" key={p._id}><div><strong>{p.name}</strong><small>{p.sku}</small></div><span className="stock-alert">{p.currentStock} / {p.minimumStock}</span></div>)}{!products.length && <Empty text="All products are above minimum stock"/>}</section></div></>;
}

function Empty({ text }) { return <div className="empty">{text}</div>; }
function Modal({ title, children, onClose }) { return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h3>{title}</h3><button onClick={onClose}>×</button></div>{children}</div></div>; }
function Field({ label, ...props }) { return <label className="field">{label}<input {...props}/></label>; }

function CustomersPage({ user }) {
  const [items, setItems] = useState([]); const [search, setSearch] = useState(""); const [modal, setModal] = useState(false); const [form, setForm] = useState({ name:"", mobile:"", email:"", businessName:"", gstNumber:"", customerType:"Wholesale", address:"", status:"Lead", notes:"" }); const [message, setMessage] = useState("");
  const load = () => api.get(`/customers?search=${encodeURIComponent(search)}`).then(r => setItems(r.data.data)); useEffect(() => {
    load();
  }, [search]);
  const submit = async e => { e.preventDefault(); try { await api.post("/customers", form); setModal(false); setForm({ name:"", mobile:"", email:"", businessName:"", gstNumber:"", customerType:"Wholesale", address:"", status:"Lead", notes:"" }); load(); setMessage("Customer added successfully"); } catch(e){ setMessage(e.response?.data?.message || "Could not save customer"); } };
  return <><div className="toolbar"><input className="search" placeholder="Search customers..." value={search} onChange={e=>setSearch(e.target.value)}/>{["ADMIN","SALES"].includes(user.role) && <button className="primary" onClick={()=>setModal(true)}>+ Add Customer</button>}</div>{message && <div className="success">{message}</div>}<div className="panel table-panel"><table><thead><tr><th>Customer</th><th>Business</th><th>Mobile</th><th>Type</th><th>Status</th><th>Follow-up</th></tr></thead><tbody>{items.map(c=><tr key={c._id}><td><strong>{c.name}</strong><small>{c.email || "—"}</small></td><td>{c.businessName}</td><td>{c.mobile}</td><td>{c.customerType}</td><td><span className={`badge ${c.status.toLowerCase()}`}>{c.status}</span></td><td>{c.followUpDate ? new Date(c.followUpDate).toLocaleDateString() : "—"}</td></tr>)}</tbody></table>{!items.length&&<Empty text="No customers found"/>}</div>{modal&&<Modal title="Add Customer" onClose={()=>setModal(false)}><form onSubmit={submit}><div className="form-grid"><Field label="Customer name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="Mobile" required value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/><Field label="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Field label="Business name" required value={form.businessName} onChange={e=>setForm({...form,businessName:e.target.value})}/><Field label="GST number" value={form.gstNumber} onChange={e=>setForm({...form,gstNumber:e.target.value})}/><label className="field">Customer type<select value={form.customerType} onChange={e=>setForm({...form,customerType:e.target.value})}><option>Retail</option><option>Wholesale</option><option>Distributor</option></select></label><label className="field">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Lead</option><option>Active</option><option>Inactive</option></select></label><Field label="Address" required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><Field label="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="primary full">Save Customer</button></form></Modal>}</>;
}

function ProductsPage({ user }) {
  const [items,setItems]=useState([]); const [modal,setModal]=useState(false); const [form,setForm]=useState({name:"",sku:"",category:"",unitPrice:"",currentStock:"",minimumStock:"",warehouseLocation:""}); const [search,setSearch]=useState(""); const load=()=>api.get(`/products?search=${encodeURIComponent(search)}`).then(r=>setItems(r.data.data)); useEffect(() => {
    load();
  }, [search]);
  const submit=async e=>{e.preventDefault(); try{await api.post("/products",form);setModal(false);setForm({name:"",sku:"",category:"",unitPrice:"",currentStock:"",minimumStock:"",warehouseLocation:""});load();}catch(e){alert(e.response?.data?.message||"Could not save product")}};
  return <><div className="toolbar"><input className="search" placeholder="Search product or SKU..." value={search} onChange={e=>setSearch(e.target.value)}/>{["ADMIN","WAREHOUSE"].includes(user.role)&&<button className="primary" onClick={()=>setModal(true)}>+ Add Product</button>}</div><div className="panel table-panel"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Unit Price</th><th>Stock</th><th>Location</th></tr></thead><tbody>{items.map(p=><tr key={p._id}><td><strong>{p.name}</strong></td><td>{p.sku}</td><td>{p.category}</td><td>₹{p.unitPrice.toLocaleString()}</td><td><span className={p.currentStock<=p.minimumStock?"stock-alert":"stock-ok"}>{p.currentStock}</span><small>min {p.minimumStock}</small></td><td>{p.warehouseLocation}</td></tr>)}</tbody></table></div>{modal&&<Modal title="Add Product" onClose={()=>setModal(false)}><form onSubmit={submit}><div className="form-grid"><Field label="Product name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="SKU" required value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><Field label="Category" required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><Field label="Unit price" type="number" required value={form.unitPrice} onChange={e=>setForm({...form,unitPrice:e.target.value})}/><Field label="Opening stock" type="number" value={form.currentStock} onChange={e=>setForm({...form,currentStock:e.target.value})}/><Field label="Minimum stock" type="number" required value={form.minimumStock} onChange={e=>setForm({...form,minimumStock:e.target.value})}/><Field label="Warehouse location" required value={form.warehouseLocation} onChange={e=>setForm({...form,warehouseLocation:e.target.value})}/></div><button className="primary full">Save Product</button></form></Modal>}</>;
}

function InventoryPage({ user }) {
  const [products,setProducts]=useState([]); const [movements,setMovements]=useState([]); const [modal,setModal]=useState(false); const [form,setForm]=useState({productId:"",quantity:"",reason:""}); const [type,setType]=useState("IN");
  const load=()=>Promise.all([api.get("/products"),api.get("/inventory/movements")]).then(([p,m])=>{setProducts(p.data.data);setMovements(m.data.data)});useEffect(() => {
    load();
  }, []);
  const submit=async e=>{e.preventDefault();try{await api.post(type==="IN"?"/inventory/stock-in":"/inventory/stock-out",form);setModal(false);setForm({productId:"",quantity:"",reason:""});load()}catch(e){alert(e.response?.data?.message||"Stock update failed")}};
  return <><div className="toolbar"><div><h3>Stock control</h3><p>Record incoming and outgoing stock with an audit trail.</p></div>{["ADMIN","WAREHOUSE"].includes(user.role)&&<button className="primary" onClick={()=>setModal(true)}>+ Stock Movement</button>}</div><div className="panel table-panel"><table><thead><tr><th>Product</th><th>SKU</th><th>Current Stock</th><th>Minimum</th><th>Warehouse</th><th>Status</th></tr></thead><tbody>{products.map(p=><tr key={p._id}><td>{p.name}</td><td>{p.sku}</td><td><strong>{p.currentStock}</strong></td><td>{p.minimumStock}</td><td>{p.warehouseLocation}</td><td>{p.currentStock<=p.minimumStock?<span className="badge inactive">Low Stock</span>:<span className="badge active">Healthy</span>}</td></tr>)}</tbody></table></div><div className="panel table-panel"><div className="panel-head"><h3>Recent stock movements</h3></div><table><thead><tr><th>Product</th><th>Type</th><th>Quantity</th><th>Reason</th><th>Created by</th><th>Date</th></tr></thead><tbody>{movements.map(m=><tr key={m._id}><td>{m.product?.name}</td><td><span className={`movement ${m.movementType.toLowerCase()}`}>{m.movementType}</span></td><td>{m.quantity}</td><td>{m.reason}</td><td>{m.createdBy?.name}</td><td>{new Date(m.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>{modal&&<Modal title="Record Stock Movement" onClose={()=>setModal(false)}><div className="toggle"><button className={type==="IN"?"selected":""} onClick={()=>setType("IN")}>Stock IN</button><button className={type==="OUT"?"selected":""} onClick={()=>setType("OUT")}>Stock OUT</button></div><form onSubmit={submit}><label className="field">Product<select required value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})}><option value="">Select product</option>{products.map(p=><option key={p._id} value={p._id}>{p.name} — {p.currentStock} in stock</option>)}</select></label><Field label="Quantity" type="number" min="1" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><Field label="Reason" required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button className="primary full">Save Movement</button></form></Modal>}</>;
}

function ChallansPage({ user }) {
  const [challans,setChallans]=useState([]);const [customers,setCustomers]=useState([]);const [products,setProducts]=useState([]);const [modal,setModal]=useState(false);const [form,setForm]=useState({customerId:"",items:[]});
  const load=()=>Promise.all([api.get("/challans"),api.get("/customers?limit=50"),api.get("/products")]).then(([c,cu,p])=>{setChallans(c.data.data);setCustomers(cu.data.data);setProducts(p.data.data)});useEffect(() => {
    load();
  }, []);
  const addItem=()=>setForm(f=>({...f,items:[...f.items,{productId:"",quantity:1}]}));
  const updateItem=(i,key,val)=>setForm(f=>({...f,items:f.items.map((x,j)=>j===i?{...x,[key]:val}:x)}));
  const create=async e=>{e.preventDefault();try{await api.post("/challans",form);setModal(false);setForm({customerId:"",items:[]});load()}catch(e){alert(e.response?.data?.message||"Could not create challan")}};
  const confirm=async id=>{if(!window.confirm("Confirm challan and reduce stock?"))return;try{await api.post(`/challans/${id}/confirm`);load()}catch(e){alert(e.response?.data?.message||"Confirmation failed")}};
  const cancel=async id=>{if(!window.confirm("Cancel this draft challan?"))return;try{await api.post(`/challans/${id}/cancel`);load()}catch(e){alert(e.response?.data?.message||"Cancellation failed")}};
  return <><div className="toolbar"><div><h3>Sales challans</h3><p>Create drafts and confirm them only after stock validation.</p></div>{["ADMIN","SALES"].includes(user.role)&&<button className="primary" onClick={()=>setModal(true)}>+ Create Challan</button>}</div><div className="panel table-panel"><table><thead><tr><th>Challan</th><th>Customer</th><th>Items</th><th>Total Qty</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{challans.map(c=><tr key={c._id}><td><strong>{c.challanNumber}</strong></td><td>{c.customer?.businessName}</td><td>{c.items.length}</td><td>{c.totalQuantity}</td><td><span className={`badge ${c.status.toLowerCase()}`}>{c.status}</span></td><td>{new Date(c.createdAt).toLocaleDateString()}</td><td>{c.status==="Draft"&&["ADMIN","SALES"].includes(user.role)&&<div className="actions"><button className="small primary" onClick={()=>confirm(c._id)}>Confirm</button><button className="small ghost" onClick={()=>cancel(c._id)}>Cancel</button></div>}</td></tr>)}</tbody></table></div>{modal&&<Modal title="Create Sales Challan" onClose={()=>setModal(false)}><form onSubmit={create}><label className="field">Customer<select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})}><option value="">Select customer</option>{customers.map(c=><option key={c._id} value={c._id}>{c.businessName} — {c.name}</option>)}</select></label><div className="items-head"><strong>Products</strong><button type="button" className="link-btn" onClick={addItem}>+ Add item</button></div>{form.items.map((item,i)=><div className="item-line" key={i}><select required value={item.productId} onChange={e=>updateItem(i,"productId",e.target.value)}><option value="">Select product</option>{products.map(p=><option key={p._id} value={p._id}>{p.name} — stock {p.currentStock}</option>)}</select><input type="number" min="1" required value={item.quantity} onChange={e=>updateItem(i,"quantity",Number(e.target.value))}/></div>)}{!form.items.length&&<div className="empty">Add at least one product.</div>}<button className="primary full" disabled={!form.items.length}>Save Draft</button></form></Modal>}</>;
}

function MovementsPage(){const[m,setM]=useState([]);useEffect(()=>{api.get("/inventory/movements").then(r=>setM(r.data.data))},[]);return <div className="panel table-panel"><div className="panel-head"><h3>Stock movement audit log</h3><span>{m.length} recent records</span></div><table><thead><tr><th>Product</th><th>SKU</th><th>Type</th><th>Qty</th><th>Reason</th><th>User</th><th>Timestamp</th></tr></thead><tbody>{m.map(x=><tr key={x._id}><td>{x.product?.name}</td><td>{x.product?.sku}</td><td><span className={`movement ${x.movementType.toLowerCase()}`}>{x.movementType}</span></td><td>{x.quantity}</td><td>{x.reason}</td><td>{x.createdBy?.name}</td><td>{new Date(x.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
function UsersPage(){const[users,setUsers]=useState([]);const[modal,setModal]=useState(false);const[form,setForm]=useState({name:"",email:"",password:"",role:"SALES"});const load=()=>api.get("/users").then(r=>setUsers(r.data.data));useEffect(() => {
  load();
}, []);const submit=async e=>{e.preventDefault();try{await api.post("/users",form);setModal(false);setForm({name:"",email:"",password:"",role:"SALES"});load()}catch(e){alert(e.response?.data?.message||"Could not create user")}};return <><div className="toolbar"><div><h3>Team & roles</h3><p>Control who can access each business module.</p></div><button className="primary" onClick={()=>setModal(true)}>+ Add User</button></div><div className="panel table-panel"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Created</th></tr></thead><tbody>{users.map(u=><tr key={u._id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td><span className="role-badge">{u.role}</span></td><td>{new Date(u.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>{modal&&<Modal title="Add Team Member" onClose={()=>setModal(false)}><form onSubmit={submit}><Field label="Name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="Email" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Field label="Password" type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><label className="field">Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><button className="primary full">Create User</button></form></Modal>}</>}

function App(){const[user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem("fundsroom_user"))}catch{return null}});const[page,setPage]=useState("dashboard");const logout=()=>{localStorage.removeItem("fundsroom_token");localStorage.removeItem("fundsroom_user");setUser(null)};if(!user)return <Login onLogin={setUser}/>;let content=page==="dashboard"?<DashboardPage/>:page==="customers"?<CustomersPage user={user}/>:page==="products"?<ProductsPage user={user}/>:page==="inventory"?<InventoryPage user={user}/>:page==="challans"?<ChallansPage user={user}/>:page==="movements"?<MovementsPage/>:<UsersPage/>;return <Layout user={user} page={page} setPage={setPage} logout={logout}>{content}</Layout>}

ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
