import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";

function App(){
  return <div className="site"><nav><div className="brand"><span>FR</span><strong>FundsRoom</strong></div><a href="#features">Features</a><a href="#workflow">Workflow</a><a className="nav-btn" href="http://localhost:3001">Open Portal</a></nav><section className="hero"><div><span className="eyebrow">MINI ERP + CRM OPERATIONS PORTAL</span><h1>Run customers, inventory and sales from one place.</h1><p>FundsRoom is a business operations portal for sales, warehouse and accounts teams. Manage customer relationships, stock movements and sales challans with clear role-based access.</p><div className="actions"><a className="primary" href="http://localhost:3001">Open Operations Portal</a><a className="secondary" href="#features">Explore features</a></div></div><div className="hero-card"><div className="hero-top"><span>Operations overview</span><span className="live">● Live</span></div><div className="mini-grid"><div><small>Customers</small><strong>248</strong></div><div><small>Products</small><strong>126</strong></div><div><small>Pending challans</small><strong>17</strong></div><div><small>Low stock</small><strong className="red">8</strong></div></div><div className="activity"><div><strong>CH-00124</strong><span>Confirmed</span></div><div><strong>Keyboard</strong><span>Stock 18</span></div><div><strong>ABC Traders</strong><span>Follow-up tomorrow</span></div></div></div></section><section id="features" className="section"><span className="eyebrow">CORE MODULES</span><h2>Everything the operations team needs.</h2><div className="cards"><Card title="Customer CRM" text="Manage leads, active customers, business details and follow-up notes."/><Card title="Inventory" text="Track products, stock levels, warehouse locations and low-stock alerts."/><Card title="Sales Challans" text="Create drafts, validate stock and confirm dispatches with an audit trail."/><Card title="Role Based Access" text="Admin, Sales, Warehouse and Accounts users see the tools they need."/></div></section><section id="workflow" className="workflow"><span className="eyebrow">BUSINESS FLOW</span><h2>From customer request to stock movement.</h2><div className="steps"><Step n="01" t="Create customer"/><Step n="02" t="Create challan draft"/><Step n="03" t="Validate stock"/><Step n="04" t="Confirm & record movement"/></div></section><footer>FundsRoom Operations Portal · Built as a full-stack case study</footer></div>
}
function Card({title,text}){return <div className="card"><div className="icon">✓</div><h3>{title}</h3><p>{text}</p></div>}
function Step({n,t}){return <div className="step"><span>{n}</span><strong>{t}</strong></div>}
ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
